services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=${DB_TYPE}
      - GITEA__database__HOST=${HOST}:${PORT}
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USERNAME}
      - GITEA__database__PASSWD=${DB_PASSWD}
      - GITEA__server__ROOT_URL=${ROOT_URL}
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ${GITEA_DATA_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner
    environment:
      - GITEA_INSTANCE_URL=http://gitea:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_REGISTRATION_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
