services:
    cyberchef:
        stdin_open: true
        tty: true
        container_name: cyberchef
        image: ghcr.io/gchq/cyberchef:latest
        ports:
          - 8070:8080
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://cyberchef.catverse.dev/health"]
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 20s
