services:
    cyberchef:
        stdin_open: true
        tty: true
        container_name: cyberchef
        image: ghcr.io/gchq/cyberchef:latest
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.cyberchef.rule=Host(`cyberchef.catverse.dev`)"
            - "traefik.http.routers.cyberchef.entrypoints=https"
            - "traefik.http.routers.cyberchef.tls=true"
            - "traefik.http.routers.cyberchef.tls.certresolver=cloudflare"
            - "traefik.http.services.cyberchef.loadbalancer.server.port=80"
        networks:
            - frontend
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://cyberchef.catverse.dev/health"]
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 20s

networks:
  frontend:
    external: true
