services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: http://10.10.10.11:8090
    ports:
      - 8090:8090
    volumes:
      - /hdd/docker/data/beszel/beszel_data:/beszel_data
      - /hdd/docker/data/beszel/beszel_socket:/beszel_socket
    healthcheck:
      test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
      interval: 120s
      start_period: 10s
      timeout: 5s
