services:
  coder:
    image: ghcr.io/coder/coder:latest
    container_name: coder
    restart: unless-stopped
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      # CODER_BOOTSTRAP_PASSWORD: ${CODER_BOOTSTRAP_PASSWORD}
      CODER_ACCESS_URL: "${CODER_ACCESS_URL}"
    group_add:
      - "120"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coder.rule=Host(`coder.catverse.dev`)"
      - "traefik.http.routers.coder.entrypoints=https"
      - "traefik.http.routers.coder.tls=true"
      - "traefik.http.routers.coder.tls.certresolver=cloudflare"
      - "traefik.http.services.coder.loadbalancer.server.port=7080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./coder:/home/coder
      - /srv/workspaces:/home/coder/workspaces
    networks:
      - backend
      - frontend
      - coder

networks:
  backend:
    external: true
  frontend:
    external: true
  coder:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
