services:
  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: mkdocs
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mkdocs.rule=Host(`docs.catverse.dev`)"
      - "traefik.http.routers.mkdocs.entrypoints=https"
      - "traefik.http.routers.mkdocs.tls=true"
      - "traefik.http.routers.mkdocs.tls.certresolver=cloudflare"
      - "traefik.http.services.mkdocs.loadbalancer.server.port=8000"
    networks:
      - frontend

networks:
  frontend:
    external: true